=== cdmngz/gov-salaries-data/templates/data-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Gov Salaries Data",
  "required": [
    "baseCurrency",
    "president",
    "vicePresident",
    "ministers",
    "congress",
    "senate",
    "royalty",
    "officials",
    "parties"
  ],
  "properties": {
    "baseCurrency": {
      "type": "string",
      "description": "The currency in which salaries are expressed, e.g. USD"
    },
    "president": { "$ref": "#/$defs/officialList" },
    "vicePresident": { "$ref": "#/$defs/officialList" },
    "ministers": { "$ref": "#/$defs/officialList" },
    "congress": { "$ref": "#/$defs/officialList" },
    "senate": { "$ref": "#/$defs/officialList" },
    "royalty": { "$ref": "#/$defs/officialList" },
    "officials": { "$ref": "#/$defs/officialList" },
    "parties": { "$ref": "#/$defs/partiesMap" }
  },
  "$defs": {
    "officialList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "gender", "salary"],
        "properties": {
          "name": { "type": "string" },
          "gender": {
            "type": "string",
            "enum": ["F", "M", "X"]
          },
          "role": {
            "type": "string"
          },
          "party": { "type": "string" },
          "district": {
            "type": "string",
            "description": "Represented state, province, area, etc."
          },
          "salary": {
            "type": "object",
            "required": ["gross", "net"],
            "properties": {
              "gross": { "type": "number" },
              "net": { "type": "number" }
            }
          },
          "details": { "$ref": "#/$defs/detailsMap" }
        }
      }
    },
    "partiesMap": {
      "type": "object",
      "description": "Party ID.",
      "additionalProperties": {
        "type": "object",
        "description": "Details for a single party.",
        "properties": {
          "name": {
            "type": "string",
            "description": "The display name of the party."
          },
          "color": {
            "type": "string",
            "description": "The color associated with the party, in HEX color format."
          },
          "en": {
            "type": "string",
            "description": "The English translation for the party."
          },
          "range": {
            "type": "number",
            "description": "1: left wing - 2: center left - 3: center - 4: center right - 5: right wing"
          }
        },
        "required": ["name", "color", "en", "range"],
        "additionalProperties": false
      }
    },
    "detailsMap": {
      "type": "object",
      "description": "Any important information related to the official, it can be text, numbers, or links.",
      "additionalProperties": {
        "anyOf": [
          { "type": "string" },
          { "type": "number" },
          { "type": "string", "format": "uri" }
        ]
      }
    }
  }
}

=== cdmngz/gov-salaries-data/ar/2025/2/data.json
{
  "baseCurrency": "USD",
  "president": [
    {
      "name": "Javier Milei",
      "gender": "M",
      "party": "LLA",
      "salary": {
        "gross": 35994,
        "net": 23396
      }
    }
  ],
  "vicePresident": [
    {
      "name": "Victoria Villarruel",
      "gender": "F",
      "party": "LLA",
      "salary": {
        "gross": 33341,
        "net": 21671
      }
    }
  ],
  "ministers": [
    {
      "name": "Luis Caputo",
      "gender": "M",
      "role": "Minister of Economy",
      "party": "LLA",
      "salary": {
        "gross": 31393,
        "net": 20405
      },
      "budget": 2200000000
    },
    {
      "name": "Sandra Petovello",
      "gender": "F",
      "role": "Minister of Human Capital",
      "party": "LLA",
      "salary": {
        "gross": 31393,
        "net": 20405
      },
      "budget": 5420000000
    },
    {
      "name": "Patricia Bullrich",
      "gender": "F",
      "role": "Minister of Security",
      "party": "PRO",
      "salary": {
        "gross": 31393,
        "net": 20405
      },
      "budget": 4280000000
    },
    {
      "name": "Mario Russo",
      "gender": "M",
      "role": "Minister of Health",
      "party": "LLA",
      "salary": {
        "gross": 31393,
        "net": 20405
      },
      "budget": 5420000000
    },
    {
      "name": "Mariano Cúneo Libarona",
      "gender": "M",
      "role": "Minister of Justice",
      "party": "LLA",
      "salary": {
        "gross": 31393,
        "net": 20405
      },
      "budget": 1460000000
    },
    {
      "name": "Luis Petri",
      "gender": "M",
      "role": "Minister of Defence",
      "party": "UCR",
      "salary": {
        "gross": 31393,
        "net": 20405
      },
      "budget": 3360000000
    },
    {
      "name": "Gerardo Werthein",
      "gender": "M",
      "role": "Minister of Foreign Affairs, International Trade and Worship",
      "party": "LLA",
      "salary": {
        "gross": 31393,
        "net": 20405
      },
      "budget": 421000000
    }
  ],
  "congress": [
    {
      "name": "Hilda Aguirre",
      "gender": "F",
      "party": "UP",
      "salary": { "gross": 35000, "net": 22750 }
    }
  ],
  "senate": [
    {
      "name": "José Mayans",
      "gender": "M",
      "district": "Formosa",
      "party": "PJ",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "María Teresa González",
      "gender": "F",
      "district": "Formosa",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Luis Petcoff Naidenoff",
      "gender": "M",
      "district": "Formosa",
      "party": "UCR",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Anabel Fernández Sagasti",
      "gender": "F",
      "district": "Mendoza",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Alfredo Cornejo",
      "gender": "M",
      "district": "Mendoza",
      "party": "UCR",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Rodolfo Suárez",
      "gender": "M",
      "district": "Mendoza",
      "party": "UCR",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Juan Carlos Romero",
      "gender": "M",
      "district": "Salta",
      "party": "PJ",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Nora Giménez",
      "gender": "F",
      "district": "Salta",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Sergio Leavy",
      "gender": "M",
      "district": "Salta",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Eduardo Costa",
      "gender": "M",
      "district": "Santa Cruz",
      "party": "UCR",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Ana María Ianni",
      "gender": "F",
      "district": "Santa Cruz",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Natalia Gadano",
      "gender": "F",
      "district": "Santa Cruz",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Martín Lousteau",
      "gender": "M",
      "district": "Buenos Aires City",
      "party": "UCR",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Guadalupe Tagliaferri",
      "gender": "F",
      "district": "Buenos Aires City",
      "party": "PRO",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Mariana Juri",
      "gender": "F",
      "district": "Buenos Aires City",
      "party": "UCR",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Edgardo Kueider",
      "gender": "M",
      "district": "Entre Ríos",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Stella Maris Olalla",
      "gender": "F",
      "district": "Entre Ríos",
      "party": "UCR",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Alfredo de Angeli",
      "gender": "M",
      "district": "Entre Ríos",
      "party": "PRO",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Carlos Espínola",
      "gender": "M",
      "district": "Corrientes",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Mercedes Valenzuela",
      "gender": "F",
      "district": "Corrientes",
      "party": "UCR",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Eduardo Vischi",
      "gender": "M",
      "district": "Corrientes",
      "party": "UCR",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Lucila Crexell",
      "gender": "F",
      "district": "Neuquén",
      "party": "JxC",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Carmen Álvarez",
      "gender": "F",
      "district": "Neuquén",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Oscar Parrilli",
      "gender": "M",
      "district": "Neuquén",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Mónica Silva",
      "gender": "F",
      "district": "Río Negro",
      "party": "JSRN",
      "salary": { "gross": 37500, "net": 24375 }
    },
    {
      "name": "Martín Doñate",
      "gender": "M",
      "district": "Río Negro",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Silvina García Larraburu",
      "gender": "F",
      "district": "Río Negro",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Claudia Ledesma Abdala",
      "gender": "F",
      "district": "Santiago del Estero",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Gerardo Montenegro",
      "gender": "M",
      "district": "Santiago del Estero",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Emilio Neder",
      "gender": "M",
      "district": "Santiago del Estero",
      "party": "UP",
      "salary": { "gross": 79800, "net": 51870 }
    },
    {
      "name": "Juan Carlos Pagotto",
      "gender": "M",
      "district": "La Rioja",
      "party": "LLA",
      "salary": {
        "gross": 37500,
        "net": 24375
      }
    },
    {
      "name": "Ricardo Guerra",
      "gender": "M",
      "district": "La Rioja",
      "party": "UP",
      "salary": {
        "gross": 79800,
        "net": 51870
      }
    },
    {
      "name": "Florencia López",
      "gender": "F",
      "district": "La Rioja",
      "party": "UP",
      "salary": {
        "gross": 79800,
        "net": 51870
      }
    },
    {
      "name": "Eugenio Artaza",
      "gender": "M",
      "district": "Chaco",
      "party": "UCR",
      "salary": {
        "gross": 37500,
        "net": 24375
      }
    },
    {
      "name": "Víctor Zimmermann",
      "gender": "M",
      "district": "Chaco",
      "party": "UCR",
      "salary": {
        "gross": 37500,
        "net": 24375
      }
    },
    {
      "name": "Alicia Fregonese",
      "gender": "F",
      "district": "Chaco",
      "party": "PRO",
      "salary": {
        "gross": 37500,
        "net": 24375
      }
    },
    {
      "name": "Bruno Olivera",
      "gender": "M",
      "district": "San Juan",
      "party": "LLA",
      "salary": {
        "gross": 37500,
        "net": 24375
      }
    },
    {
      "name": "Rubén Uñac",
      "gender": "M",
      "district": "San Juan",
      "party": "UP",
      "salary": {
        "gross": 79800,
        "net": 51870
      }
    },
    {
      "name": "María Celeste Giménez",
      "gender": "F",
      "district": "San Juan",
      "party": "UP",
      "salary": {
        "gross": 79800,
        "net": 51870
      }
    },
    {
      "name": "Cristina López",
      "gender": "F",
      "district": "Tierra del Fuego",
      "party": "UP",
      "salary": {
        "gross": 79800,
        "net": 51870
      }
    },
    {
      "name": "María Eugenia Duré",
      "gender": "F",
      "district": "Tierra del Fuego",
      "party": "UP",
      "salary": {
        "gross": 79800,
        "net": 51870
      }
    },
    {
      "name": "Pablo Blanco",
      "gender": "M",
      "district": "Tierra del Fuego",
      "party": "UCR",
      "salary": {
        "gross": 37500,
        "net": 24375
      }
    },
    {
      "name": "Maximiliano Abad",
      "gender": "M",
      "district": "Buenos Aires",
      "party": "UCR",
      "salary": {
        "gross": 37500,
        "net": 24375
      }
    },
    {
      "name": "Wado de Pedro",
      "gender": "M",
      "district": "Buenos Aires",
      "party": "UP",
      "salary": {
        "gross": 79800,
        "net": 51870
      }
    },
